[package]
name    = "xtensa-core-isa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow        = "1.0"
enum-as-inner = "0.3"
regex         = "1.5"
strum         = "0.23"
strum_macros  = "0.23"
