[package]
name    = "xtensa-core-isa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow       = "1.0.53"
enum-as-inner = "0.3.3"
nom          = "7.1.0"
strum        = "0.23.0"
strum_macros = "0.23.1"
